# Generated by Django 3.2.9 on 2021-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form1', models.IntegerField(default=10)),
                ('form2', models.IntegerField(default=5)),
            ],
        ),
    ]
