# Generated by Django 3.2.9 on 2021-11-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.IntegerField(default=0, verbose_name='現在の進捗')),
                ('total', models.IntegerField(default=100, verbose_name='全ステップ数')),
            ],
        ),
    ]
