# Generated by Django 3.2.9 on 2021-11-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(default=30)),
                ('number2', models.IntegerField(default=20)),
                ('gen', models.IntegerField(default=100)),
            ],
        ),
    ]
