# Generated by Django 3.2.9 on 2021-11-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_numbergen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='total',
            field=models.IntegerField(verbose_name='全ステップ数'),
        ),
    ]
